### ISSUE TITLE
Password reset for user results in 404 + python.org vs. PyPI users

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#371]
Originally reported by: **Kay (Bitbucket: [kerstin](https://bitbucket.org/kerstin), GitHub: [kerstin](https://github.com/kerstin))**

----------------------------------------

Hi,

1) I'm getting a 404 when trying to reset the PW for an account *which could be mine*. I'm not entirely sure if it is, but apparently there is no way to reset one's pw by using one's e-mail address? I don't know if the password reset form is half-broken or if it's a problem with that particular user name; using invalid user names results in a valid response in any case.

2) Is there a way to reset the PW using one's e-mail address? If not, why not, and is this going to change in the future? As someone who uses different user names and e-mail addresses on the internet, this seems very impractical to me.

3) Do python.org and PyPI share users or are they separate from each other? I'd like to avoid account duplication on the one hand, but might not want to be stuck with a particular user name on both pages forever, on the other. (So, 3a) is it possible to change one's PyPI user name later?)

PS: The fact you use two systems to keep track of tickets is confusing, are they meant for the same thing? One is labelled *support*, the other *bug reports* on PyPI's main page, but I saw bug report tickets on the former as well.

Anyway, sticking this here as the 404 is definitely a bug (and I already have an account here but not on SourceForge...).

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/371

**Comment by berkerpeksag** [comment]
1. I think this is resolved by https://github.com/pypa/pypi-legacy/commit/7b37f8f809c2aff660b5b841f8e95fd6c6260700.

2. AFAIK, you can only reset your password by using your username. pypi.python.org will be replaced by https://github.com/pypa/warehouse soon so I doubt we can add this feature to the legacy PyPI. You can create an issue over pypa/warehouse though.

3. No, they don't. This was discussed before so I'd say there is a chance that it will happen at some point in the future.

**Comment by kerstin** [comment]
@berkerpeksag just a quick, if late, follow-up:

1. No, I just tried again and the problem persists. Maybe this is an account for which no e-mail address exists in the system, or which got deleted and is now blocked or something like that.
2. Yeah, looks like it. And makes sense. Will PyPA be able to handle this better? (I now have 2 user names on PyPI because as it turns out, I did already have one registered...)
2. I see, thanks.
