### ISSUE TITLE
Authorization issue when trying to upload my package.

### ISSUE THREAD

**Issue by tylerlong** [pypa/pypi-legacy#590]
### Issue 1: unable to authenticate with correct credentials

I can login https://pypi.python.org/pypi with my username password so I am sure they are correct

But I cannot upload my package. I always get 

```
Upload failed (403): Invalid or non-existent authentication information.
error: Upload failed (403): Invalid or non-existent authentication information.
```

### Issue 2: unable to reset my password

```
We need to know who you are, so please choose either:
 1. use your existing login,
 2. register as a new user,
 3. have the server generate a new password for you (and email it to you), or
 4. quit
Your selection [default 1]:
3
Your email address: xxxxxyyyyy@gmail.com
Server response (404): Not Found
```

### Issue 3: unable to create a new account

```
We need to know who you are, so please choose either:
 1. use your existing login,
 2. register as a new user,
 3. have the server generate a new password for you (and email it to you), or
 4. quit
Your selection [default 1]:
2
Username: xxxxyyyy
Password:
 Confirm:
   EMail: xxxxyyyy@gmail.com
Registering xxxxyyyy to https://upload.pypi.org/legacy/
Server response (404): Not Found
```

**Comment by glefait** [comment]
Same here. I was able to register through web https://pypi.python.org/pypi?%3Aaction=register_form
but neither authentification or upload worked.

**Comment by KayEss** [comment]
I'm getting this 403 error when trying to upload a package now. It worked fine on Feb 22nd, but it doesn't work today (8th Mar).

    Creating tar archive
    removing 'django-async-0.7.2' (and everything under it)
    running upload
    Password: 
    Submitting dist/django-async-0.7.2.tar.gz to https://upload.pypi.org/legacy/
    Upload failed (403): Invalid or non-existent authentication information.
    error: Upload failed (403): Invalid or non-existent authentication information.

**Comment by KayEss** [comment]
Before giving up I thought I'd try one last thing. I changed to python3 and that seemed to do the trick:

    python3 setup.py sdist upload

**Comment by demonno** [comment]
I had same issue while publishing package and `~/.pypirc` configuration below worked well.

    [distutils]
     index-servers =
         pypi
    
     [pypi]
     repository: https://upload.pypi.org/legacy/
     username: 
     password:

**Comment by awanish-tiwari** [comment]
This api is legacy https://pypi.python.org/pypi has no longer supported by pypi.
you can add something at ~/ .pypirc, it should work

[distutils]
index-servers =
     pypi

[pypi]
repository:https://upload.pypi.org/legacy/
username: Your Username
password: Your Password

**Comment by shubhamkatariya** [comment]
This api is legacy https://pypi.python.org/pypi has no longer supported by pypi.
you can add something at ~/ .pypirc, it should work

[distutils]
index-servers =
pypi

[pypi]
repository:https://upload.pypi.org/legacy/
username: Your Username
password: Your Password

and use this for upload

python setup.py register sdist upload

This will be register and upload in one action.

**Comment by jinfagang** [comment]
@KayEss Your solution gots this error:

```
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    install_requires=['colorama', 'opencv-python', 'requests']
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/upload.py", line 63, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/upload.py", line 161, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

twine is broken definately.

**Comment by berkerpeksag** [comment]
@jinfagang that traceback is from distutils, not twine and you can fix it by making the `classifiers` field in your project's `setup.py` a list instead of a tuple. This distutils error has been fixed in Python 3.7.

**Comment by xiangbobopopo** [comment]
still  not wording.

**Comment by di** [comment]
Since there's lots of different issues happening in this thread, I'd like to ask anyone still having problems to open a new, individual issue at https://github.com/pypa/warehouse/issues instead of commenting here.

**Comment by BeautifulCodes** [comment]
Still Doesn't work.

**Comment by jamadden** [comment]
@BeautifulCodes please open a specific issue on the warehouse tracker indicated above. PyPI personnel no longer monitor this tracker as this code base is abandoned in favor of warehouse.
